FROM fedora as source

COPY neuron.repo /etc/yum.repos.d/neuron.repo
RUN yum clean all
RUN  rpm --import https://yum.repos.neuron.amazonaws.com/GPG-PUB-KEY-AMAZON-AWS-NEURON.PUB
RUN yum install -y aws-neuronx-dkms-2.*
RUN yum install aws-neuronx-collectives-2.* -y
RUN yum install aws-neuronx-runtime-lib-2.* -y
RUN yum install aws-neuronx-tools-2.* -y

ENV PATH="/opt/aws/neuron/bin:${PATH}"
